-- GENERATED by scripts/emit_config_sql.py from config/bank_demo.yaml. Do not edit by hand.
-- Institution: Kestrel Valley Bank (kvb_merged). SYNTHETIC DEMO.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

CREATE OR REPLACE TABLE GOLD.CONFIG_PARAM (name VARCHAR, num_value DOUBLE, text_value VARCHAR)
  COMMENT = 'Institution thresholds and settings from config/bank_demo.yaml';
INSERT INTO GOLD.CONFIG_PARAM (name, num_value, text_value) VALUES
  ('capital.total_risk_based_capital_usd', 265000000, '265000000'),
  ('institution.as_of_date', NULL, '2026-08-31'),
  ('risk_queue.legacy_score_weight', 0.6, '0.6'),
  ('risk_queue.min_score_for_new_alert', 20, '20'),
  ('risk_queue.pattern_lookback_days', 184, '184'),
  ('risk_queue.window_days', 30, '30'),
  ('thresholds.alert_sla_days', 30, '30'),
  ('thresholds.cross_core_cash_total_usd', 50000, '50000'),
  ('thresholds.cross_core_cash_window_days', 30, '30'),
  ('thresholds.ctr_cash_threshold_usd', 10000, '10000'),
  ('thresholds.dormancy_days', 365, '365'),
  ('thresholds.kyc_cash_min_usd', 10000, '10000'),
  ('thresholds.kyc_cash_multiple', 3, '3'),
  ('thresholds.kyc_consistent_max_multiple', 1.5, '1.5'),
  ('thresholds.legacy_per_core_cash_30d_usd', 30000, '30000'),
  ('thresholds.near_threshold_min_count', 4, '4'),
  ('thresholds.rapid_in_out_hours', 48, '48'),
  ('thresholds.rapid_in_out_min_inflow_usd', 25000, '25000'),
  ('thresholds.rapid_in_out_pct_out', 0.9, '0.9'),
  ('thresholds.reactivation_inflow_usd', 10000, '10000'),
  ('thresholds.structuring_band_low_usd', 7000, '7000');

CREATE OR REPLACE TABLE GOLD.CONFIG_RISK_RULE (rule_code VARCHAR, weight DOUBLE, description VARCHAR)
  COMMENT = 'Risk rules and weights from config/bank_demo.yaml';
INSERT INTO GOLD.CONFIG_RISK_RULE (rule_code, weight, description) VALUES
  ('XCORE_CASH_30D', 35, 'Combined cash deposits across both cores exceed the 30-day threshold'),
  ('CTR_AGGREGATION_MISSED', 30, 'Same-day cash across cores exceeds the CTR threshold with no CTR filed'),
  ('NEAR_THRESHOLD_CASH', 20, 'Repeated cash deposits just below the CTR threshold'),
  ('RAPID_IN_OUT', 25, 'Most of a large inflow leaves within the rapid-movement window'),
  ('DORMANT_REACTIVATION', 20, 'Large inflow into an account dormant for more than the dormancy period'),
  ('KYC_MISMATCH', 15, 'Observed cash far exceeds the expected monthly cash in the KYC profile'),
  ('KYC_INCONSISTENT_ACROSS_CORES', 10, 'Occupation or business differs between the two cores'' KYC records'),
  ('KYC_CONSISTENT_CASH', -20, 'Mitigating: cash activity is within the expected monthly cash in the KYC profile');
