"""Split the BSA/AML policy PDF into one chunk per numbered section, keeping the page number for citations.

  python -m search.extract_policy                      # writes sql/50_search/50_policy_chunks.sql

No AI: text comes from pypdf, sections from the policy's own numbering ("4.2 Aggregation.").
Snowflake's document parsing is a Cortex AI feature, so extraction runs here and the SQL loads the result.
"""
import re
import sys
from pathlib import Path

from pypdf import PdfReader

REPO = Path(__file__).resolve().parent.parent
DEFAULT_PDF = REPO / "data" / "out" / "demo" / "documents" / "bsa_aml_policy.pdf"
DOCUMENT = "documents/bsa_aml_policy.pdf"

HEADER = re.compile(r"^(Kestrel Valley Bank BSA/AML Program Policy.*|Page \d+)$")
# "4.2 Aggregation. Multiple ..." (subsection) or "4. Currency transaction reporting" (section) or "Appendix A. ..."
SUB = re.compile(r"^(\d+\.\d+)\s+([A-Z][^.]{2,60})\.\s*(.*)$")
SEC = re.compile(r"^(\d+)\.\s+([A-Z][A-Za-z ,/\-]{2,70})$")
APP = re.compile(r"^(Appendix [A-Z])\.\s+(.*)$")


def extract(pdf=DEFAULT_PDF):
    reader = PdfReader(str(pdf))
    chunks, cur = [], None
    in_contents = False
    parent = ""

    def close():
        if cur and " ".join(cur["lines"]).strip():
            cur["text"] = re.sub(r"\s+", " ", " ".join(cur["lines"])).strip()
            chunks.append(cur)

    for page_no, page in enumerate(reader.pages, start=1):
        for raw in (page.extract_text() or "").splitlines():
            line = raw.strip()
            if not line or HEADER.match(line):
                continue
            if line == "Contents":
                in_contents = True
                continue
            if in_contents:
                if page_no == 1:
                    continue                      # table of contents lines are not content
                in_contents = False
            m_sub, m_sec, m_app = SUB.match(line), SEC.match(line), APP.match(line)
            if m_sub or m_sec or m_app:
                close()
                if m_sub:
                    sec_id, title, rest = m_sub.groups()
                    cur = {"section": f"{sec_id} {title}", "parent": parent, "page": page_no,
                           "lines": [f"{title}. {rest}"]}
                elif m_sec:
                    sec_id, title = m_sec.groups()
                    parent = f"{sec_id}. {title}"
                    cur = {"section": parent, "parent": "", "page": page_no, "lines": [f"{title}."]}
                else:
                    sec_id, title = m_app.groups()
                    parent = f"{sec_id}. {title}"
                    cur = {"section": parent, "parent": "", "page": page_no, "lines": [f"{title}."]}
            else:
                if cur is None:
                    cur = {"section": "Title page", "parent": "", "page": page_no, "lines": []}
                cur["lines"].append(line)
                cur.setdefault("pages", set()).add(page_no)
    close()
    # a section with only a heading ("4. Currency transaction reporting.") adds nothing on its own
    chunks = [c for c in chunks if len(c["text"].split()) > 4 or c["section"] == "Title page"]
    for i, c in enumerate(chunks, 1):
        c["chunk_id"] = f"POL-{i:03d}"
        pages = sorted(c.pop("pages", {c["page"]}) | {c["page"]})
        c["page_to"] = pages[-1]
        c.pop("lines", None)
    return chunks


def q(s):
    return str(s).replace("'", "''")


def render(chunks):
    rows = ",\n".join(
        f"  ('{c['chunk_id']}', '{DOCUMENT}', '{q(c['section'])}', '{q(c['parent'])}', {c['page']}, {c['page_to']}, "
        f"'{q(c['text'])}')"
        for c in chunks)
    return f"""-- GENERATED by search/extract_policy.py from {DOCUMENT}. Do not edit by hand.
-- One row per numbered policy section, with the page it starts on (for citations). SYNTHETIC DEMO DOCUMENT.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

CREATE SCHEMA IF NOT EXISTS SEARCH COMMENT = 'Document search (F5): keyword search with citations, no AI';
CREATE OR REPLACE TABLE SEARCH.POLICY_CHUNK (
    chunk_id VARCHAR, document VARCHAR, section VARCHAR, parent_section VARCHAR, page INTEGER, page_to INTEGER,
    chunk_text VARCHAR
);
INSERT INTO SEARCH.POLICY_CHUNK (chunk_id, document, section, parent_section, page, page_to, chunk_text) VALUES
{rows};
"""


def main():
    pdf = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PDF
    chunks = extract(pdf)
    out = REPO / "sql" / "50_search" / "50_policy_chunks.sql"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(chunks))
    print(f"wrote {out}: {len(chunks)} sections")
    for c in chunks:
        print(f"  p{c['page']}  {c['section'][:50]:50s} {len(c['text'].split())} words")


if __name__ == "__main__":
    main()
