-- GENERATED by onboarding/onboard.py (rules, no AI). Review mapping.yaml first.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;


CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_PARTY (
    "party_uuid" VARCHAR,
    "party_kind" VARCHAR,
    "full_name" VARCHAR,
    "dob" VARCHAR,
    "ssn_token" VARCHAR,
    "street" VARCHAR,
    "city_state_zip" VARCHAR,
    "phone_num" VARCHAR,
    "email_addr" VARCHAR,
    "relationship_start" VARCHAR,
    "kyc_risk" VARCHAR,
    "employer_or_industry" VARCHAR,
    "home_branch" VARCHAR,
    _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

COPY INTO RISK_COPILOT.BRONZE.CORE_B_PARTY ("party_uuid", "party_kind", "full_name", "dob", "ssn_token", "street", "city_state_zip", "phone_num", "email_addr", "relationship_start", "kyc_risk", "employer_or_industry", "home_branch", _SOURCE_FILE, _SOURCE_ROW, _LOADED_AT)
  FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @RISK_COPILOT.BRONZE.RAW_STAGE/core_b/party.csv.gz)
  FILE_FORMAT = (FORMAT_NAME = 'RISK_COPILOT.BRONZE.FF_CSV_GZ')
  ON_ERROR = ABORT_STATEMENT FORCE = TRUE;

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_DEPOSIT_ACCOUNT (
    "acct_ref" VARCHAR,
    "party_uuid" VARCHAR,
    "product_name" VARCHAR,
    "branch_name" VARCHAR,
    "opened_on" VARCHAR,
    "closed_on" VARCHAR,
    "acct_status" VARCHAR,
    "dormant_since" VARCHAR,
    "reactivated_on" VARCHAR,
    "ledger_balance" VARCHAR,
    "rate_pct" VARCHAR,
    _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

COPY INTO RISK_COPILOT.BRONZE.CORE_B_DEPOSIT_ACCOUNT ("acct_ref", "party_uuid", "product_name", "branch_name", "opened_on", "closed_on", "acct_status", "dormant_since", "reactivated_on", "ledger_balance", "rate_pct", _SOURCE_FILE, _SOURCE_ROW, _LOADED_AT)
  FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @RISK_COPILOT.BRONZE.RAW_STAGE/core_b/deposit_account.csv.gz)
  FILE_FORMAT = (FORMAT_NAME = 'RISK_COPILOT.BRONZE.FF_CSV_GZ')
  ON_ERROR = ABORT_STATEMENT FORCE = TRUE;

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_TXN (
    "txn_uuid" VARCHAR,
    "acct_ref" VARCHAR,
    "txn_timestamp" VARCHAR,
    "amount" VARCHAR,
    "dr_cr" VARCHAR,
    "txn_type_desc" VARCHAR,
    "channel_desc" VARCHAR,
    "branch_name" VARCHAR,
    "ctr_filed" VARCHAR,
    "counterparty" VARCHAR,
    "counterparty_institution" VARCHAR,
    _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

COPY INTO RISK_COPILOT.BRONZE.CORE_B_TXN ("txn_uuid", "acct_ref", "txn_timestamp", "amount", "dr_cr", "txn_type_desc", "channel_desc", "branch_name", "ctr_filed", "counterparty", "counterparty_institution", _SOURCE_FILE, _SOURCE_ROW, _LOADED_AT)
  FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @RISK_COPILOT.BRONZE.RAW_STAGE/core_b/txn.csv.gz)
  FILE_FORMAT = (FORMAT_NAME = 'RISK_COPILOT.BRONZE.FF_CSV_GZ')
  ON_ERROR = ABORT_STATEMENT FORCE = TRUE;
