-- GENERATED by onboarding/onboard.py (rules, no AI). Review mapping.yaml first.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;


CREATE OR REPLACE VIEW SILVER.CORE_B_CUSTOMER AS
SELECT 'core_b:' || "party_uuid" AS record_id,
       'core_b' AS source_system,
       "party_uuid" AS source_key,
       DECODE("party_kind", 'ORG', 'ORG', 'PERSON', 'PERSON') AS party_kind,
       IFF(DECODE("party_kind", 'ORG', 'ORG', 'PERSON', 'PERSON') = 'ORG', NULL, UPPER(TRIM(SPLIT_PART("full_name", ',', 1)))) AS last_name,
       IFF(DECODE("party_kind", 'ORG', 'ORG', 'PERSON', 'PERSON') = 'ORG', NULL, UPPER(SPLIT_PART(TRIM(SPLIT_PART("full_name", ',', 2)), ' ', 1))) AS first_name,
       TRY_TO_DATE("dob", 'MM/DD/YYYY') AS birth_date,
       NULLIF(LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM("ssn_token"), '^[A-Za-z]+_', ''), '[^0-9A-Fa-f]', '')), '') AS tax_token,
       UPPER(TRIM("street")) AS street,
       UPPER(TRIM(SPLIT_PART("city_state_zip", ',', 1))) AS city,
       UPPER(SPLIT_PART(TRIM(SPLIT_PART("city_state_zip", ',', 2)), ' ', 1)) AS state,
       SPLIT_PART(TRIM(SPLIT_PART("city_state_zip", ',', 2)), ' ', 2) AS zip,
       RIGHT(REGEXP_REPLACE("phone_num", '[^0-9]', ''), 10) AS phone,
       LOWER(TRIM("email_addr")) AS email,
       TRY_TO_DATE("relationship_start", 'YYYY-MM-DD') AS customer_since,
       _SOURCE_FILE AS source_file,
       _SOURCE_ROW AS source_row
  FROM BRONZE.CORE_B_PARTY;

CREATE OR REPLACE VIEW SILVER.CORE_B_ACCOUNT AS
SELECT 'core_b:' || "acct_ref" AS record_id,
       'core_b' AS source_system,
       "acct_ref" AS source_key,
       'core_b:' || "party_uuid" AS customer_key,
       DECODE("product_name", 'Business Checking', 'CHECKING', 'Certificate of Deposit', 'CERTIFICATE', 'Everyday Checking', 'CHECKING', 'Money Market', 'MONEY_MARKET', 'Statement Savings', 'SAVINGS') AS product_type,
       TRY_TO_DATE("opened_on", 'YYYY-MM-DD') AS opened_on,
       DECODE("acct_status", 'CLOSED', 'CLOSED', 'DORMANT', 'DORMANT', 'OPEN', 'OPEN') AS status,
       TO_NUMBER("ledger_balance", 38, 2) AS balance_usd,
       _SOURCE_FILE AS source_file,
       _SOURCE_ROW AS source_row
  FROM BRONZE.CORE_B_DEPOSIT_ACCOUNT;

CREATE OR REPLACE VIEW SILVER.CORE_B_TRANSACTION AS
SELECT 'core_b:' || "txn_uuid" AS record_id,
       'core_b' AS source_system,
       "txn_uuid" AS source_key,
       TRY_TO_TIMESTAMP_NTZ(LEFT("txn_timestamp", 19)) AS posted_at,
       DECODE("txn_type_desc", 'ACH Credit', 'ACH_CREDIT', 'ACH Debit', 'ACH_DEBIT', 'ATM Withdrawal', 'ATM_WITHDRAWAL', 'Cash Deposit', 'CASH_DEPOSIT', 'Cash Withdrawal', 'CASH_WITHDRAWAL', 'Check Paid', 'CHECK_PAID', 'Debit Card Purchase', 'CARD_PURCHASE', 'Incoming Wire', 'WIRE_IN', 'Interest Credit', 'INTEREST', 'Outgoing Wire', 'WIRE_OUT', 'Transfer In', 'TRANSFER_IN', 'Transfer Out', 'TRANSFER_OUT') AS txn_type,
       IFF("dr_cr" = 'C', 1, -1) * TO_NUMBER("amount", 38, 2) AS amount_signed_usd,
       DECODE("channel_desc", 'ATM', 'ATM', 'Mobile App', 'MOBILE', 'Online Banking', 'ONLINE', 'System', 'SYSTEM', 'Teller', 'BRANCH') AS channel,
       'core_b:' || "acct_ref" AS account_key,
       _SOURCE_FILE AS source_file,
       _SOURCE_ROW AS source_row
  FROM BRONZE.CORE_B_TXN;
