-- GENERATED by onboarding/onboard.py (rules, no AI). Review mapping.yaml first.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;


CREATE OR REPLACE VIEW SILVER.CORE_C_CUSTOMER AS
SELECT 'core_c:' || "custId" AS record_id,
       'core_c' AS source_system,
       "custId" AS source_key,
       UPPER(TRIM("givenName")) AS first_name,
       UPPER(TRIM("familyName")) AS last_name,
       TRY_TO_DATE("birthDate", 'YYYY/MM/DD') AS birth_date,
       NULLIF(LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM("taxRef"), '^[A-Za-z]+_', ''), '[^0-9A-Fa-f]', '')), '') AS tax_token,
       UPPER(TRIM("addressLine")) AS street,
       UPPER(TRIM("cityName")) AS city,
       UPPER(TRIM("stateCode")) AS state,
       "postalCode" AS zip,
       RIGHT(REGEXP_REPLACE("mobile", '[^0-9]', ''), 10) AS phone,
       TO_DATE(TO_TIMESTAMP_NTZ(TRY_TO_NUMBER("createdTs"))) AS customer_since,
       _SOURCE_FILE AS source_file,
       _SOURCE_ROW AS source_row
  FROM BRONZE.CORE_C_CUSTOMERS;

CREATE OR REPLACE VIEW SILVER.CORE_C_ACCOUNT AS
SELECT 'core_c:' || "accountId" AS record_id,
       'core_c' AS source_system,
       "accountId" AS source_key,
       DECODE("accountType", 'CHK', 'CHECKING', 'SVG', 'SAVINGS') AS product_type,
       TRY_TO_DATE("openedDate", 'YYYY/MM/DD') AS opened_on,
       TO_NUMBER("balanceAmt", 38, 2) AS balance_usd,
       'core_c:' || "custId" AS customer_key,
       _SOURCE_FILE AS source_file,
       _SOURCE_ROW AS source_row
  FROM BRONZE.CORE_C_ACCOUNTS;

CREATE OR REPLACE VIEW SILVER.CORE_C_TRANSACTION AS
SELECT 'core_c:' || "postingId" AS record_id,
       'core_c' AS source_system,
       "postingId" AS source_key,
       'core_c:' || "accountId" AS account_key,
       TO_TIMESTAMP_NTZ(TRY_TO_NUMBER("postedTs")) AS posted_at,
       DECODE("typeCode", 'CSHIN', 'CASH_DEPOSIT', 'CSHOUT', 'CASH_WITHDRAWAL', 'EFTIN', 'ACH_CREDIT', 'EFTOUT', 'ACH_DEBIT', 'POS', 'CARD_PURCHASE') AS txn_type,
       TO_NUMBER("amt", 38, 2) AS amount_signed_usd,
       DECODE("channel", 'app', 'MOBILE', 'atm', 'ATM', 'branch', 'BRANCH', 'web', 'ONLINE') AS channel,
       _SOURCE_FILE AS source_file,
       _SOURCE_ROW AS source_row
  FROM BRONZE.CORE_C_POSTINGS;
