-- GENERATED by scripts/emit_bronze_sql.py from data_gen/schemas.py. Do not edit by hand.
-- ALL DATA IS SYNTHETIC. Fictional institutions and people.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_CUSTOMERS (
    "CIF_NO" VARCHAR COMMENT '9-digit customer information file number',
    "CUST_TYPE" VARCHAR COMMENT 'I = individual, B = business',
    "FIRST_NM" VARCHAR COMMENT 'First name (individuals)',
    "MID_INIT" VARCHAR COMMENT 'Middle initial',
    "LAST_NM" VARCHAR COMMENT 'Last name (individuals)',
    "SFX" VARCHAR COMMENT 'Suffix, e.g. JR, SR',
    "BUS_NM" VARCHAR COMMENT 'Legal business name (businesses)',
    "BIRTH_DT" VARCHAR COMMENT 'Date of birth YYYYMMDD; 00000000 when missing',
    "TAX_ID_TKN" VARCHAR COMMENT 'Tokenised SSN/EIN, upper-case hex',
    "ADDR_LN1" VARCHAR COMMENT 'Street address, abbreviated suffix',
    "CITY" VARCHAR COMMENT 'City',
    "ST" VARCHAR COMMENT 'State code',
    "ZIP5" VARCHAR COMMENT '5-digit ZIP',
    "PHONE_NO" VARCHAR COMMENT '10 digits, no punctuation',
    "EMAIL_ADDR" VARCHAR COMMENT 'Email',
    "CUST_SINCE_DT" VARCHAR COMMENT 'Relationship start YYYYMMDD',
    "RISK_RTG" VARCHAR COMMENT 'KYC risk rating L/M/H',
    "OCCUP_DESC" VARCHAR COMMENT 'Occupation or line of business',
    "HOME_BR_CD" VARCHAR COMMENT 'Home branch code',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Kestrel Valley legacy core: customer master (CIF) - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_ACCOUNTS (
    "ACCT_NO" VARCHAR COMMENT '10-digit account number',
    "CIF_NO" VARCHAR COMMENT 'Owner CIF',
    "PROD_CD" VARCHAR COMMENT 'DDA, SAV, MMA, CD',
    "BR_CD" VARCHAR COMMENT 'Branch code',
    "OPEN_DT" VARCHAR COMMENT 'YYYYMMDD',
    "CLOSE_DT" VARCHAR COMMENT 'YYYYMMDD or blank',
    "ACCT_STAT" VARCHAR COMMENT 'A active, D dormant, C closed',
    "DORM_FLAG_DT" VARCHAR COMMENT 'Date flagged dormant YYYYMMDD or blank',
    "REACT_DT" VARCHAR COMMENT 'Date reactivated YYYYMMDD or blank',
    "CUR_BAL_CENTS" VARCHAR COMMENT 'Ledger balance in cents at as-of date',
    "INT_RATE_PCT" VARCHAR COMMENT 'Interest rate, percent',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Kestrel Valley legacy core: deposit accounts - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_LOANS (
    "LOAN_NO" VARCHAR COMMENT 'Loan number L + 9 digits',
    "CIF_NO" VARCHAR COMMENT 'Borrower CIF',
    "LOAN_TYP" VARCHAR COMMENT 'AUTO, MORT, HELOC, PERS, CRE, CI',
    "BR_CD" VARCHAR COMMENT 'Branch code',
    "ORIG_DT" VARCHAR COMMENT 'YYYYMMDD',
    "MAT_DT" VARCHAR COMMENT 'YYYYMMDD',
    "ORIG_AMT_CENTS" VARCHAR COMMENT 'Original amount in cents',
    "CUR_PRIN_CENTS" VARCHAR COMMENT 'Outstanding principal in cents',
    "INT_RATE_PCT" VARCHAR COMMENT 'Interest rate, percent',
    "COLL_TYP" VARCHAR COMMENT 'Collateral type code',
    "OWNER_OCC_FLG" VARCHAR COMMENT 'Y/N owner-occupied (real estate)',
    "DPD" VARCHAR COMMENT 'Days past due',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Kestrel Valley legacy core: loans - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_TXNS (
    "TXN_ID" VARCHAR COMMENT '14-digit transaction id',
    "ACCT_NO" VARCHAR COMMENT 'Account number',
    "POST_DT" VARCHAR COMMENT 'Posting date YYYYMMDD',
    "POST_TM" VARCHAR COMMENT 'Posting time HHMMSS, local',
    "TXN_CD" VARCHAR COMMENT 'CDEP, CWDR, ATMW, ACHC, ACHD, WIRI, WIRO, CHKP, CARD, XFRI, XFRO, INTC',
    "AMT_CENTS" VARCHAR COMMENT 'Signed amount in cents (credit positive)',
    "CHNL_CD" VARCHAR COMMENT 'BR branch, ATM, OLB online, MOB mobile, SYS system',
    "BR_CD" VARCHAR COMMENT 'Branch where conducted, blank if not in branch',
    "CTR_FLG" VARCHAR COMMENT 'Y if a CTR was filed for this cash transaction',
    "CPTY_NM" VARCHAR COMMENT 'Counterparty name',
    "CPTY_BANK" VARCHAR COMMENT 'Counterparty institution',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Kestrel Valley legacy core: posted transactions - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_AML_ALERTS (
    "ALERT_ID" VARCHAR COMMENT 'Numeric alert id',
    "CIF_NO" VARCHAR COMMENT 'Customer CIF',
    "ACCT_NO" VARCHAR COMMENT 'Primary account',
    "RULE_CD" VARCHAR COMMENT 'LCT01 large cash, STR02 structuring, VEL03 velocity, WIR04 high-risk wire, RMV05 rapid movement, DRM06 dormant reactivation',
    "ALERT_DT" VARCHAR COMMENT 'YYYYMMDD',
    "ALERT_SCORE" VARCHAR COMMENT 'Legacy score 0-100',
    "ALERT_STAT" VARCHAR COMMENT 'OPEN, WIP, CLOSED',
    "DISPO_CD" VARCHAR COMMENT 'FP false positive, NSR no SAR after review, SAR SAR filed, blank if open',
    "CLOSE_DT" VARCHAR COMMENT 'YYYYMMDD or blank',
    "ASSIGNED_TO" VARCHAR COMMENT 'Investigator user id',
    "BR_CD" VARCHAR COMMENT 'Branch of the account',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Kestrel Valley legacy transaction-monitoring alerts - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_BRANCHES (
    "BR_CD" VARCHAR COMMENT 'Branch code',
    "BR_NM" VARCHAR COMMENT 'Branch name',
    "CITY" VARCHAR COMMENT 'City',
    "ST" VARCHAR COMMENT 'State',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Kestrel Valley branches - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_A_CONTROL_TOTALS (
    "FILE_NM" VARCHAR COMMENT 'Extract file',
    "REC_CNT" VARCHAR COMMENT 'Record count',
    "AMT_TOTAL_CENTS" VARCHAR COMMENT 'Sum of the file''s amount column in cents, blank if none',
    "AS_OF_DT" VARCHAR COMMENT 'YYYYMMDD',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Extract control totals written by the Core A extract job - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_PARTY (
    "party_uuid" VARCHAR COMMENT 'UUID v4',
    "party_kind" VARCHAR COMMENT 'PERSON or ORG',
    "full_name" VARCHAR COMMENT 'LAST, FIRST M for persons; legal name for orgs',
    "dob" VARCHAR COMMENT 'MM/DD/YYYY or blank',
    "ssn_token" VARCHAR COMMENT 'Tokenised SSN/EIN: tkn_ + lower-case hex, or blank',
    "street" VARCHAR COMMENT 'Street address, long-form suffix',
    "city_state_zip" VARCHAR COMMENT 'City, ST 12345',
    "phone_num" VARCHAR COMMENT '(NNN) NNN-NNNN',
    "email_addr" VARCHAR COMMENT 'Email',
    "relationship_start" VARCHAR COMMENT 'ISO date',
    "kyc_risk" VARCHAR COMMENT '1 (low) to 5 (high)',
    "employer_or_industry" VARCHAR COMMENT 'Employer, occupation or industry',
    "home_branch" VARCHAR COMMENT 'Branch name',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Pellbrook legacy core: parties - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_DEPOSIT_ACCOUNT (
    "acct_ref" VARCHAR COMMENT 'PB- + 8 digits',
    "party_uuid" VARCHAR COMMENT 'Owner party',
    "product_name" VARCHAR COMMENT 'Everyday Checking, Business Checking, Statement Savings, Money Market, Certificate of Deposit',
    "branch_name" VARCHAR COMMENT 'Branch name',
    "opened_on" VARCHAR COMMENT 'ISO date',
    "closed_on" VARCHAR COMMENT 'ISO date or blank',
    "acct_status" VARCHAR COMMENT 'OPEN, DORMANT, CLOSED',
    "dormant_since" VARCHAR COMMENT 'ISO date or blank',
    "reactivated_on" VARCHAR COMMENT 'ISO date or blank',
    "ledger_balance" VARCHAR COMMENT 'Decimal dollars',
    "rate_pct" VARCHAR COMMENT 'Interest rate, percent',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Pellbrook legacy core: deposit accounts - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_LOAN (
    "note_number" VARCHAR COMMENT 'LN-YYYY-######',
    "party_uuid" VARCHAR COMMENT 'Borrower party',
    "product_name" VARCHAR COMMENT 'Auto Loan, Residential Mortgage, Home Equity Line, Personal Loan, Commercial Real Estate, Commercial & Industrial',
    "branch_name" VARCHAR COMMENT 'Branch name',
    "booked_on" VARCHAR COMMENT 'ISO date',
    "maturity_on" VARCHAR COMMENT 'ISO date',
    "original_amount" VARCHAR COMMENT 'Decimal dollars',
    "principal_outstanding" VARCHAR COMMENT 'Decimal dollars',
    "interest_rate_pct" VARCHAR COMMENT 'Percent',
    "collateral_desc" VARCHAR COMMENT 'Free-text collateral description',
    "owner_occupied" VARCHAR COMMENT 'true/false',
    "days_delinquent" VARCHAR COMMENT 'Days past due',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Pellbrook legacy core: loans - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_TXN (
    "txn_uuid" VARCHAR COMMENT 'UUID v4',
    "acct_ref" VARCHAR COMMENT 'Account',
    "txn_timestamp" VARCHAR COMMENT 'ISO 8601 with UTC offset',
    "amount" VARCHAR COMMENT 'Positive decimal dollars',
    "dr_cr" VARCHAR COMMENT 'D debit, C credit',
    "txn_type_desc" VARCHAR COMMENT 'Cash Deposit, Cash Withdrawal, ATM Withdrawal, ACH Credit, ACH Debit, Incoming Wire, Outgoing Wire, Check Paid, Debit Card Purchase, Transfer In, Transfer Out, Interest Credit',
    "channel_desc" VARCHAR COMMENT 'Teller, ATM, Online Banking, Mobile App, System',
    "branch_name" VARCHAR COMMENT 'Branch where conducted, blank if not in branch',
    "ctr_filed" VARCHAR COMMENT 'true/false',
    "counterparty" VARCHAR COMMENT 'Counterparty name',
    "counterparty_institution" VARCHAR COMMENT 'Counterparty institution',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Pellbrook legacy core: transactions - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_CASE_ALERT (
    "case_ref" VARCHAR COMMENT 'AL-2026-######',
    "party_uuid" VARCHAR COMMENT 'Party',
    "acct_ref" VARCHAR COMMENT 'Primary account',
    "scenario_name" VARCHAR COMMENT 'Monitoring scenario',
    "created_at" VARCHAR COMMENT 'ISO timestamp',
    "priority" VARCHAR COMMENT 'P1, P2, P3',
    "state" VARCHAR COMMENT 'NEW, IN_REVIEW, ESCALATED, CLOSED',
    "outcome" VARCHAR COMMENT 'NOT_SUSPICIOUS, NO_SAR_AFTER_REVIEW, SAR_FILED, or blank',
    "closed_at" VARCHAR COMMENT 'ISO timestamp or blank',
    "analyst" VARCHAR COMMENT 'Analyst name',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Pellbrook legacy transaction-monitoring alerts - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_BRANCH (
    "branch_name" VARCHAR COMMENT 'Branch name',
    "branch_city" VARCHAR COMMENT 'City',
    "branch_state" VARCHAR COMMENT 'State',
    "opened_year" VARCHAR COMMENT 'Year opened',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Pellbrook branches - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_B_CONTROL_TOTALS (
    "file_name" VARCHAR COMMENT 'Extract file',
    "record_count" VARCHAR COMMENT 'Record count',
    "amount_total" VARCHAR COMMENT 'Sum of the file''s amount column in dollars, blank if none',
    "as_of" VARCHAR COMMENT 'ISO date',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Extract control totals written by the Core B extract job - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_C_CUSTOMERS (
    "custId" VARCHAR COMMENT 'C- + 7 digits',
    "givenName" VARCHAR COMMENT 'Given name',
    "familyName" VARCHAR COMMENT 'Family name',
    "birthDate" VARCHAR COMMENT 'YYYY/MM/DD',
    "taxRef" VARCHAR COMMENT 'Tax token with dashes',
    "addressLine" VARCHAR COMMENT 'Street',
    "cityName" VARCHAR COMMENT 'City',
    "stateCode" VARCHAR COMMENT 'State',
    "postalCode" VARCHAR COMMENT 'ZIP',
    "mobile" VARCHAR COMMENT '+1 NNN NNN NNNN',
    "createdTs" VARCHAR COMMENT 'Epoch seconds',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Third core (onboarding-skill test only): customers - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_C_ACCOUNTS (
    "accountId" VARCHAR COMMENT 'Account id',
    "custId" VARCHAR COMMENT 'Owner',
    "accountType" VARCHAR COMMENT 'CHK, SVG',
    "balanceAmt" VARCHAR COMMENT 'Dollars',
    "openedDate" VARCHAR COMMENT 'YYYY/MM/DD',
    "statusCode" VARCHAR COMMENT '1 open, 2 dormant, 9 closed',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Third core: accounts - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.CORE_C_POSTINGS (
    "postingId" VARCHAR COMMENT 'Posting id',
    "accountId" VARCHAR COMMENT 'Account',
    "postedTs" VARCHAR COMMENT 'Epoch seconds',
    "amt" VARCHAR COMMENT 'Signed dollars',
    "typeCode" VARCHAR COMMENT 'CSHIN, CSHOUT, EFTIN, EFTOUT, POS',
    "channel" VARCHAR COMMENT 'Channel',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Third core: postings - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.DOC_INVESTIGATOR_NOTES (
    "note_id" VARCHAR COMMENT 'Note id',
    "core" VARCHAR COMMENT 'core_a or core_b',
    "alert_ref" VARCHAR COMMENT 'Alert id in that core',
    "customer_ref" VARCHAR COMMENT 'CIF_NO or party_uuid',
    "author" VARCHAR COMMENT 'Investigator',
    "created_at" VARCHAR COMMENT 'ISO timestamp',
    "note_text" VARCHAR COMMENT 'Note text (synthetic)',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Investigator case notes from both legacy monitoring systems - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.BRONZE.DOC_KYC_SUMMARIES (
    "kyc_id" VARCHAR COMMENT 'KYC record id',
    "core" VARCHAR COMMENT 'core_a or core_b',
    "customer_ref" VARCHAR COMMENT 'CIF_NO or party_uuid',
    "review_date" VARCHAR COMMENT 'ISO date',
    "risk_rating" VARCHAR COMMENT 'Low, Medium, High',
    "occupation_or_business" VARCHAR COMMENT 'Occupation or business',
    "expected_monthly_cash_usd" VARCHAR COMMENT 'Expected monthly cash',
    "expected_monthly_wires_usd" VARCHAR COMMENT 'Expected monthly wires',
    "source_of_funds" VARCHAR COMMENT 'Declared source of funds',
    "summary_text" VARCHAR COMMENT 'Summary (synthetic)',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'KYC profile summaries from both cores - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.EVAL.GT_PERSON_MAP (
    "person_id" VARCHAR COMMENT 'True person id',
    "core" VARCHAR COMMENT 'core_a, core_b, core_c',
    "customer_ref" VARCHAR COMMENT 'Source key',
    "record_role" VARCHAR COMMENT 'Role of the record',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Every source customer record mapped to its true person - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.EVAL.GT_DUPLICATE_LINKS (
    "person_id" VARCHAR COMMENT 'True person',
    "core_a_cif" VARCHAR COMMENT 'CIF_NO',
    "core_b_party_uuid" VARCHAR COMMENT 'party_uuid',
    "tier" VARCHAR COMMENT 'A clean, B variant, C hard',
    "variation" VARCHAR COMMENT 'What differs',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'True cross-core duplicate identities - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.EVAL.GT_LOOKALIKE_PAIRS (
    "pair_id" VARCHAR COMMENT 'Pair id',
    "lookalike_type" VARCHAR COMMENT 'JR_SR, TWINS, SAME_NAME_DOB',
    "core_a_cif" VARCHAR COMMENT 'CIF_NO',
    "core_b_party_uuid" VARCHAR COMMENT 'party_uuid',
    "person_id_a" VARCHAR COMMENT 'Person',
    "person_id_b" VARCHAR COMMENT 'Person',
    "core_b_token_missing" VARCHAR COMMENT 'true/false',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Different people who look alike across cores; must never be merged - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.EVAL.GT_INJECTED_PATTERNS (
    "pattern_id" VARCHAR COMMENT 'Pattern id',
    "pattern_type" VARCHAR COMMENT 'Type',
    "person_id" VARCHAR COMMENT 'True person',
    "cores" VARCHAR COMMENT 'Cores involved',
    "customer_refs" VARCHAR COMMENT 'Source keys; semicolon separated',
    "account_refs" VARCHAR COMMENT 'Accounts; semicolon separated',
    "window_start" VARCHAR COMMENT 'ISO date',
    "window_end" VARCHAR COMMENT 'ISO date',
    "total_amount_usd" VARCHAR COMMENT 'Pattern amount',
    "expected_reason_codes" VARCHAR COMMENT 'Reason codes the risk engine should give',
    "legacy_alert_refs" VARCHAR COMMENT 'Existing legacy alerts, if any',
    "detail" VARCHAR COMMENT 'Detail',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Every injected risk pattern - SYNTHETIC DATA';

CREATE OR REPLACE TABLE RISK_COPILOT.EVAL.GT_DQ_ISSUES (
    "issue_id" VARCHAR COMMENT 'Issue id',
    "issue_type" VARCHAR COMMENT 'Type',
    "core" VARCHAR COMMENT 'Core',
    "table_name" VARCHAR COMMENT 'Bronze table',
    "record_key" VARCHAR COMMENT 'Record key',
    "field" VARCHAR COMMENT 'Field',
    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file',
    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file',
    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'
) COMMENT = 'Injected data-quality issues - SYNTHETIC DATA';
