"""Render semantic/questions.yaml into sql/40_semantic/41_question_catalog.sql (SEMANTIC.QUESTION_CATALOG).

  python scripts/emit_question_catalog.py

The app reads the catalogue from Snowflake, so reviewed SQL lives in one governed table.
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from semantic.catalog import load_catalog  # noqa: E402


def q(s):
    return str(s).replace("'", "''")


def render():
    rows = []
    for c in load_catalog():
        sql = c["sql"].strip()
        assert ";" not in sql, f"{c['id']}: catalogue SQL must be a single statement without ';'"
        rows.append("  ('{}', '{}', '{}', '{}', '{}', '{}')".format(
            q(c["id"]), q(c["question"]), q(json.dumps(c.get("keywords", []))), q(c.get("definition", "")),
            q(sql), q(c.get("headline", ""))))
    body = ",\n".join(rows)
    return f"""-- GENERATED by scripts/emit_question_catalog.py from semantic/questions.yaml. Do not edit by hand.
-- F3 without AI: every answer comes from reviewed SQL chosen from this catalogue.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

CREATE OR REPLACE TABLE SEMANTIC.QUESTION_CATALOG (
    question_id VARCHAR, question VARCHAR, keywords_json VARCHAR, metric VARCHAR, answer_sql VARCHAR, headline VARCHAR
);
INSERT INTO SEMANTIC.QUESTION_CATALOG (question_id, question, keywords_json, metric, answer_sql, headline) VALUES
{body};

GRANT SELECT ON TABLE SEMANTIC.QUESTION_CATALOG TO ROLE RISK_ANALYST;
"""


def main():
    out = REPO / "sql" / "40_semantic" / "41_question_catalog.sql"
    out.write_text(render())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
