"""Render Snowflake Bronze DDL and COPY statements from data_gen/schemas.py.

  python scripts/emit_bronze_sql.py        # rewrites sql/10_bronze/10_tables.sql and 11_copy.sql

Bronze keeps every source column as VARCHAR exactly as delivered, plus lineage
columns (_SOURCE_FILE, _SOURCE_ROW, _LOADED_AT) so every Silver and Gold row can
be traced back to one line of one file.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from data_gen.schemas import ALL_TABLES  # noqa: E402

DB = "RISK_COPILOT"
HEADER = """-- GENERATED by scripts/emit_bronze_sql.py from data_gen/schemas.py. Do not edit by hand.
-- ALL DATA IS SYNTHETIC. Fictional institutions and people.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;
"""


def q(s):
    return s.replace("'", "''")


def schema_for(t):
    return "EVAL" if t.source == "ground_truth" else "BRONZE"


def stage_for(t):
    return f"{DB}.EVAL.GT_STAGE" if t.source == "ground_truth" else f"{DB}.BRONZE.RAW_STAGE"


def tables_sql():
    out = [HEADER]
    for t in ALL_TABLES:
        cols = [f'    "{c}" VARCHAR COMMENT \'{q(d)}\'' for c, d in t.columns]
        cols += ["    _SOURCE_FILE VARCHAR COMMENT 'Stage path of the source file'",
                 "    _SOURCE_ROW NUMBER COMMENT 'Row number within the source file'",
                 "    _LOADED_AT TIMESTAMP_LTZ COMMENT 'Load time'"]
        out.append(f"CREATE OR REPLACE TABLE {DB}.{schema_for(t)}.{t.name} (\n" + ",\n".join(cols)
                   + f"\n) COMMENT = '{q(t.description)} - SYNTHETIC DATA';\n")
    return "\n".join(out)


def copy_sql():
    out = [HEADER]
    for t in ALL_TABLES:
        n = len(t.columns)
        sel = ", ".join(f"${i}" for i in range(1, n + 1))
        cols = ", ".join(f'"{c}"' for c, _ in t.columns)
        out.append(
            f"COPY INTO {DB}.{schema_for(t)}.{t.name} ({cols}, _SOURCE_FILE, _SOURCE_ROW, _LOADED_AT)\n"
            f"  FROM (SELECT {sel}, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()\n"
            f"        FROM @{stage_for(t)}/{t.path})\n"
            f"  FILE_FORMAT = (FORMAT_NAME = '{DB}.BRONZE.FF_CSV_GZ')\n"
            f"  ON_ERROR = ABORT_STATEMENT FORCE = TRUE;\n")
    return "\n".join(out)


def main():
    d = REPO / "sql" / "10_bronze"
    d.mkdir(parents=True, exist_ok=True)
    (d / "10_tables.sql").write_text(tables_sql())
    (d / "11_copy.sql").write_text(copy_sql())
    print(f"wrote {d / '10_tables.sql'} and {d / '11_copy.sql'} for {len(ALL_TABLES)} tables")


if __name__ == "__main__":
    main()
