"""Render the institution config (config/bank_demo.yaml) into Snowflake config tables.

  python scripts/emit_config_sql.py      # rewrites sql/30_gold/30_config.sql

The risk engine reads thresholds and rule weights from these tables, so a second
bank runs from its own YAML with no SQL change (F14).
"""
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent


def q(s):
    return str(s).replace("'", "''")


def render(cfg_path=REPO / "config" / "bank_demo.yaml"):
    cfg = yaml.safe_load(Path(cfg_path).read_text())
    params = {f"thresholds.{k}": v for k, v in cfg["thresholds"].items()}
    params.update({f"risk_queue.{k}": v for k, v in cfg["risk_queue"].items()})
    params["capital.total_risk_based_capital_usd"] = cfg["capital"]["total_risk_based_capital_usd"]
    params["institution.as_of_date"] = cfg["institution"]["as_of_date"]
    rows = []
    for k, v in sorted(params.items()):
        num = v if isinstance(v, (int, float)) and not isinstance(v, bool) else None
        rows.append(f"  ('{q(k)}', {num if num is not None else 'NULL'}, '{q(v)}')")
    rules = [f"  ('{q(r['code'])}', {r['weight']}, '{q(r['description'])}')" for r in cfg["risk_rules"]]
    sep = ",\n"
    params_sql, rules_sql = sep.join(rows), sep.join(rules)
    return f"""-- GENERATED by scripts/emit_config_sql.py from config/bank_demo.yaml. Do not edit by hand.
-- Institution: {cfg['institution']['display_name']} ({cfg['institution']['id']}). SYNTHETIC DEMO.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

CREATE OR REPLACE TABLE GOLD.CONFIG_PARAM (name VARCHAR, num_value DOUBLE, text_value VARCHAR)
  COMMENT = 'Institution thresholds and settings from config/bank_demo.yaml';
INSERT INTO GOLD.CONFIG_PARAM (name, num_value, text_value) VALUES
{params_sql};

CREATE OR REPLACE TABLE GOLD.CONFIG_RISK_RULE (rule_code VARCHAR, weight DOUBLE, description VARCHAR)
  COMMENT = 'Risk rules and weights from config/bank_demo.yaml';
INSERT INTO GOLD.CONFIG_RISK_RULE (rule_code, weight, description) VALUES
{rules_sql};
"""


def main():
    out = REPO / "sql" / "30_gold" / "30_config.sql"
    out.write_text(render())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
