-- GENERATED by scripts/emit_question_catalog.py from semantic/questions.yaml. Do not edit by hand.
-- F3 without AI: every answer comes from reviewed SQL chosen from this catalogue.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

CREATE OR REPLACE TABLE SEMANTIC.QUESTION_CATALOG (
    question_id VARCHAR, question VARCHAR, keywords_json VARCHAR, metric VARCHAR, answer_sql VARCHAR, headline VARCHAR
);
INSERT INTO SEMANTIC.QUESTION_CATALOG (question_id, question, keywords_json, metric, answer_sql, headline) VALUES
  ('G01', 'How many customer records does each core hold?', '["customer", "records", "each", "core", "hold", "count", "how many customers per core", "customer file"]', 'customer records', 'SELECT source_system AS core, COUNT(*) AS customer_records
  FROM SEMANTIC.V_CUSTOMER_RECORD
 GROUP BY source_system
 ORDER BY source_system', 'Core A holds {customer_records:,} customer records; see the table for Core B.'),
  ('G02', 'How many unique customers do we have across both cores after matching?', '["unique", "customers", "distinct", "deduplicated", "after matching", "entity resolution", "both cores", "real customers", "people"]', 'unique customers', 'SELECT (SELECT COUNT(*) FROM GOLD.PARTY) AS unique_customers,
       (SELECT COUNT(*) FROM SEMANTIC.V_CUSTOMER_RECORD) AS customer_records,
       (SELECT COUNT(*) FROM GOLD.PARTY WHERE cores = 2) AS customers_in_both_cores', '{unique_customers:,} unique customers from {customer_records:,} records; {customers_in_both_cores:,} bank with both cores.'),
  ('G03', 'How many AML alerts were generated across both cores in August 2026?', '["aml", "alerts", "generated", "august", "month", "raised", "alert volume", "how many alerts", "last month"]', 'alert volume', 'SELECT COUNT(*) AS alerts,
       SUM(IFF(source_system = ''core_a'', 1, 0)) AS core_a_alerts,
       SUM(IFF(source_system = ''core_b'', 1, 0)) AS core_b_alerts
  FROM SEMANTIC.V_ALERT
 WHERE alert_date BETWEEN DATE ''2026-08-01'' AND DATE ''2026-08-31''', '{alerts:,} alerts in August 2026 (Core A {core_a_alerts:,}, Core B {core_b_alerts:,}).'),
  ('G04', 'What was the false-positive rate for alerts closed in Q2 2026?', '[false, "positive", "rate", "fp", "closed", "q2", "quarter", "second quarter", "not suspicious", "alert quality"]', 'false-positive rate', 'SELECT COUNT(*) AS closed,
       SUM(IFF(is_false_positive, 1, 0)) AS false_positives,
       ROUND(100.0 * SUM(IFF(is_false_positive, 1, 0)) / COUNT(*), 1) AS false_positive_rate_pct
  FROM SEMANTIC.V_ALERT
 WHERE closed_on BETWEEN DATE ''2026-04-01'' AND DATE ''2026-06-30''', '{false_positive_rate_pct}% of the {closed:,} alerts closed in Q2 2026 were false positives.'),
  ('G05', 'Which three branches had the most alerts in the last 90 days, and how many each?', '["branches", "branch", "most", "alerts", "last 90 days", "top three", "three months", "busiest", "where"]', 'alert volume', 'SELECT branch, COUNT(*) AS alerts
  FROM SEMANTIC.V_ALERT
 WHERE alert_date > DATE ''2026-08-31'' - 90
 GROUP BY branch
 ORDER BY alerts DESC, branch
 LIMIT 3', '{branch} had the most alerts in the last 90 days ({alerts}); ties are listed alphabetically.'),
  ('G06', 'How many alerts are still open more than 30 days after they were raised?', '["alerts", "still", "open", "more than 30 days", "overdue", "sla", "backlog", "aged", "older than a month", "past due alerts"]', 'open alert', 'SELECT SUM(IFF(alert_date < DATE ''2026-08-01'', 1, 0)) AS open_over_30_days,
       COUNT(*) AS open_total
  FROM SEMANTIC.V_ALERT
 WHERE is_open', '{open_over_30_days} of {open_total} open alerts were raised more than 30 days ago.'),
  ('G07', 'What was the total value of cash deposits across both cores in August 2026?', '["total", "value", "cash", "deposits", "cash in", "august", "both cores", "deposited", "how much cash"]', 'cash in', 'SELECT ROUND(SUM(amount_usd), 2) AS cash_deposits_usd,
       ROUND(SUM(IFF(source_system = ''core_a'', amount_usd, 0)), 2) AS core_a_usd,
       ROUND(SUM(IFF(source_system = ''core_b'', amount_usd, 0)), 2) AS core_b_usd
  FROM SEMANTIC.V_CASH
 WHERE cash_direction = ''IN'' AND posted_date BETWEEN DATE ''2026-08-01'' AND DATE ''2026-08-31''', '${cash_deposits_usd:,.2f} of cash was deposited across both cores in August 2026.'),
  ('G08', 'What was the total value of cash withdrawals, including ATM, across both cores in August 2026?', '["cash", "withdrawals", "atm", "cash out", "withdrawn", "august", "total value", "both cores"]', 'cash out', 'SELECT ROUND(SUM(amount_usd), 2) AS cash_withdrawals_usd,
       ROUND(SUM(IFF(txn_type = ''ATM_WITHDRAWAL'', amount_usd, 0)), 2) AS atm_usd,
       ROUND(SUM(IFF(txn_type = ''CASH_WITHDRAWAL'', amount_usd, 0)), 2) AS teller_usd
  FROM SEMANTIC.V_CASH
 WHERE cash_direction = ''OUT'' AND posted_date BETWEEN DATE ''2026-08-01'' AND DATE ''2026-08-31''', '${cash_withdrawals_usd:,.2f} of cash was withdrawn (teller and ATM) in August 2026.'),
  ('G09', 'What is the loan-to-deposit ratio as of 31 August 2026?', '["loan", "deposit", "ratio", "ltd", "loan to deposit", "liquidity", "loans versus deposits"]', 'loan-to-deposit ratio', 'SELECT ROUND(l.usd, 2) AS loans_usd, ROUND(d.usd, 2) AS deposits_usd,
       ROUND(100.0 * l.usd / d.usd, 1) AS loan_to_deposit_pct
  FROM (SELECT SUM(principal_usd) AS usd FROM SEMANTIC.V_LOAN) l
 CROSS JOIN (SELECT SUM(balance_usd) AS usd FROM SEMANTIC.V_DEPOSIT) d', 'The loan-to-deposit ratio is {loan_to_deposit_pct}% (${loans_usd:,.0f} loans / ${deposits_usd:,.0f} deposits).'),
  ('G10', 'What is non-owner-occupied CRE as a percentage of total risk-based capital?', '["cre", "commercial real estate", "non owner occupied", "capital", "concentration", "risk based capital", "percentage"]', 'CRE concentration', 'SELECT ROUND(SUM(IFF(l.is_non_owner_occupied_cre, l.principal_usd, 0)), 2) AS non_owner_occupied_cre_usd,
       MAX(c.num_value) AS total_risk_based_capital_usd,
       ROUND(100.0 * SUM(IFF(l.is_non_owner_occupied_cre, l.principal_usd, 0)) / MAX(c.num_value), 1) AS cre_to_capital_pct,
       ROUND(100.0 * SUM(IFF(l.is_non_owner_occupied_cre, l.principal_usd, 0)) / SUM(l.principal_usd), 1) AS cre_share_of_loans_pct
  FROM SEMANTIC.V_LOAN l
 CROSS JOIN (SELECT num_value FROM GOLD.CONFIG_PARAM WHERE name = ''capital.total_risk_based_capital_usd'') c', 'Non-owner-occupied CRE is {cre_to_capital_pct}% of total risk-based capital ({cre_share_of_loans_pct}% of loans).'),
  ('G11', 'What are total deposit balances in each core?', '["deposit", "balances", "each core", "total deposits", "how much deposits", "by core", "funding"]', 'deposit balances', 'SELECT source_system AS core, ROUND(SUM(balance_usd), 2) AS deposits_usd, COUNT(*) AS accounts
  FROM SEMANTIC.V_DEPOSIT
 GROUP BY source_system
 ORDER BY source_system', 'Core A holds ${deposits_usd:,.2f} in deposits; see the table for Core B.'),
  ('G12', 'How many deposit accounts are dormant as of 31 August 2026?', '["dormant", "accounts", "inactive", "deposit accounts", "how many dormant"]', 'dormant account', 'SELECT SUM(IFF(is_dormant, 1, 0)) AS dormant_accounts,
       SUM(IFF(is_dormant AND source_system = ''core_a'', 1, 0)) AS core_a,
       SUM(IFF(is_dormant AND source_system = ''core_b'', 1, 0)) AS core_b
  FROM SEMANTIC.V_DEPOSIT', '{dormant_accounts} deposit accounts are dormant (Core A {core_a}, Core B {core_b}).'),
  ('G13', 'Who are the top five customers by cash deposited across both cores in the last 30 days?', '["top", "five", "customers", "cash", "deposited", "last 30 days", "biggest", "largest", "who deposited most"]', 'cash in', 'SELECT display_name AS customer,
       ROUND(SUM(IFF(source_system = ''core_a'', amount_usd, 0)), 2) AS core_a_usd,
       ROUND(SUM(IFF(source_system = ''core_b'', amount_usd, 0)), 2) AS core_b_usd,
       ROUND(SUM(amount_usd), 2) AS cash_deposits_usd
  FROM SEMANTIC.V_CASH
 WHERE cash_direction = ''IN'' AND posted_date BETWEEN DATE ''2026-08-02'' AND DATE ''2026-08-31''
 GROUP BY party_id, display_name
 ORDER BY cash_deposits_usd DESC
 LIMIT 5', '{customer} deposited the most cash in the last 30 days (${cash_deposits_usd:,.2f}).'),
  ('G14', 'What was the average number of days to close alerts closed in Q2 2026?', '["average", "days", "close", "alerts", "q2", "time to close", "how long", "resolution time", "quarter"]', 'days to close', 'SELECT ROUND(AVG(days_to_close), 1) AS avg_days_to_close, COUNT(*) AS closed
  FROM SEMANTIC.V_ALERT
 WHERE closed_on BETWEEN DATE ''2026-04-01'' AND DATE ''2026-06-30''', 'Alerts closed in Q2 2026 took {avg_days_to_close} days on average to close.'),
  ('G15', 'How many loans are 90 or more days past due, and what is their outstanding principal?', '["loans", "90 days", "past due", "delinquent", "non performing", "overdue loans", "principal", "credit quality"]', '90+ days past due', 'SELECT SUM(IFF(is_90_plus_past_due, 1, 0)) AS loans_90_plus,
       ROUND(SUM(IFF(is_90_plus_past_due, principal_usd, 0)), 2) AS principal_usd
  FROM SEMANTIC.V_LOAN', '{loans_90_plus} loans are 90+ days past due, with ${principal_usd:,.2f} outstanding.'),
  ('D01', 'Which customers moved more than $50k in cash across both cores in 30 days, and what do their KYC files say?', '["customers", "moved", "more than 50k", 50000, "cash", "both cores", "30 days", "kyc", "structuring", "what do their kyc files say", "over threshold"]', 'cash in', 'WITH c AS (
    SELECT party_id,
           SUM(IFF(source_system = ''core_a'', amount_usd, 0)) AS core_a_usd,
           SUM(IFF(source_system = ''core_b'', amount_usd, 0)) AS core_b_usd,
           SUM(amount_usd) AS total_usd
      FROM SEMANTIC.V_CASH
     WHERE cash_direction = ''IN'' AND posted_date BETWEEN DATE ''2026-08-02'' AND DATE ''2026-08-31''
       AND party_id IS NOT NULL
     GROUP BY party_id
    HAVING SUM(amount_usd) > 50000
),
k AS (
    SELECT party_id,
           LISTAGG(source_system || '': '' || occupation || '', expects $'' || CAST(CAST(expected_monthly_cash_usd AS BIGINT) AS VARCHAR) || ''/month'', '' | '')
             WITHIN GROUP (ORDER BY source_system) AS kyc_says,
           MAX(expected_monthly_cash_usd) AS expected_monthly_cash_usd
      FROM GOLD.KYC_PROFILE WHERE party_id IS NOT NULL GROUP BY party_id
)
SELECT p.display_name AS customer, ROUND(c.core_a_usd, 2) AS core_a_usd, ROUND(c.core_b_usd, 2) AS core_b_usd,
       ROUND(c.total_usd, 2) AS total_cash_usd, k.kyc_says,
       IFF(c.total_usd <= 1.5 * k.expected_monthly_cash_usd, ''Explained by KYC'', ''Not explained by KYC'') AS kyc_verdict,
       COALESCE(s.risk_score, 0) AS risk_score, s.top_reasons
  FROM c
  JOIN GOLD.PARTY p ON p.party_id = c.party_id
  LEFT JOIN k ON k.party_id = c.party_id
  LEFT JOIN GOLD.RISK_SCORE s ON s.party_id = c.party_id
 ORDER BY risk_score DESC, total_cash_usd DESC', '{row_count} customers moved over $50,000 in cash in 30 days; the table shows which their KYC explains.'),
  ('D02', 'On which days did a customer''s cash deposits across both cores exceed $10,000 with no CTR filed?', '["ctr", "currency transaction report", "same day", "aggregation", 10000, "10k", "no ctr filed", "missed ctr", "days", "both cores"]', 'cash in', 'SELECT MAX(display_name) AS customer, posted_date AS business_day,
       ROUND(SUM(IFF(source_system = ''core_a'', amount_usd, 0)), 2) AS core_a_usd,
       ROUND(SUM(IFF(source_system = ''core_b'', amount_usd, 0)), 2) AS core_b_usd,
       ROUND(SUM(amount_usd), 2) AS total_usd
  FROM SEMANTIC.V_CASH
 WHERE cash_direction = ''IN'' AND party_id IS NOT NULL
 GROUP BY party_id, posted_date
HAVING COUNT(DISTINCT source_system) = 2 AND SUM(amount_usd) > 10000 AND MAX(IFF(ctr_filed, 1, 0)) = 0
 ORDER BY business_day, customer', '{row_count} customer-days had same-day cash over $10,000 across the two cores with no CTR (policy 4.2).'),
  ('D03', 'Which alerts should my team work first today, and why?', '["work first", "priority", "prioritise", "prioritize", "queue", "today", "highest risk", "riskiest", "why", "triage", "top alerts"]', 'risk score', 'SELECT queue_rank, display_name AS customer, origin, priority_score, reasons, evidence
  FROM GOLD.ALERT_QUEUE
 WHERE queue_rank <= 10
 ORDER BY queue_rank', 'Start with {customer} (priority {priority_score:.0f}): {reasons}.');

GRANT SELECT ON TABLE SEMANTIC.QUESTION_CATALOG TO ROLE RISK_ANALYST;
