-- GENERATED by coco_skills/onboard_core/onboard.py (rules, no AI). Review mapping.yaml first.
USE ROLE RISK_ADMIN;
USE WAREHOUSE RISK_WH;
USE DATABASE RISK_COPILOT;

SELECT 'customer' AS entity, 'rows' AS check_name, COUNT(*) AS failures, 'information' AS rule FROM SILVER.CORE_B_CUSTOMER
UNION ALL
SELECT 'customer', 'key is null', COUNT(*), 'must be 0' FROM SILVER.CORE_B_CUSTOMER WHERE source_key IS NULL
UNION ALL
SELECT 'customer', 'duplicate keys', COUNT(*) - COUNT(DISTINCT source_key), 'must be 0' FROM SILVER.CORE_B_CUSTOMER
UNION ALL
SELECT 'customer', 'party_kind not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_CUSTOMER v JOIN BRONZE.CORE_B_PARTY b ON b._SOURCE_ROW = v.source_row WHERE v.party_kind IS NULL AND b."party_kind" IS NOT NULL
UNION ALL
SELECT 'customer', 'birth_date not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_CUSTOMER v JOIN BRONZE.CORE_B_PARTY b ON b._SOURCE_ROW = v.source_row WHERE v.birth_date IS NULL AND b."dob" IS NOT NULL AND v.party_kind IS DISTINCT FROM 'ORG'
UNION ALL
SELECT 'customer', 'customer_since not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_CUSTOMER v JOIN BRONZE.CORE_B_PARTY b ON b._SOURCE_ROW = v.source_row WHERE v.customer_since IS NULL AND b."relationship_start" IS NOT NULL
UNION ALL
SELECT 'customer', 'birth_date in the future or before 1900', COUNT(*), 'report' FROM SILVER.CORE_B_CUSTOMER v WHERE v.birth_date > CURRENT_DATE OR v.birth_date < DATE '1900-01-01'
UNION ALL
SELECT 'customer', 'zip not 5 digits or 00000', COUNT(*), 'report' FROM SILVER.CORE_B_CUSTOMER v WHERE v.zip IS NOT NULL AND (NOT REGEXP_LIKE(v.zip, '[0-9]{5}') OR v.zip = '00000')
UNION ALL
SELECT 'customer', 'tax token not 16 hex characters', COUNT(*), 'report' FROM SILVER.CORE_B_CUSTOMER v WHERE v.tax_token IS NOT NULL AND NOT REGEXP_LIKE(v.tax_token, '[0-9a-f]{16}')
UNION ALL
SELECT 'customer', 'phone not 10 digits', COUNT(*), 'report' FROM SILVER.CORE_B_CUSTOMER v WHERE v.phone IS NOT NULL AND NOT REGEXP_LIKE(v.phone, '[0-9]{10}')
UNION ALL
SELECT 'account' AS entity, 'rows' AS check_name, COUNT(*) AS failures, 'information' AS rule FROM SILVER.CORE_B_ACCOUNT
UNION ALL
SELECT 'account', 'key is null', COUNT(*), 'must be 0' FROM SILVER.CORE_B_ACCOUNT WHERE source_key IS NULL
UNION ALL
SELECT 'account', 'duplicate keys', COUNT(*) - COUNT(DISTINCT source_key), 'must be 0' FROM SILVER.CORE_B_ACCOUNT
UNION ALL
SELECT 'account', 'product_type not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_ACCOUNT v JOIN BRONZE.CORE_B_DEPOSIT_ACCOUNT b ON b._SOURCE_ROW = v.source_row WHERE v.product_type IS NULL AND b."product_name" IS NOT NULL
UNION ALL
SELECT 'account', 'opened_on not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_ACCOUNT v JOIN BRONZE.CORE_B_DEPOSIT_ACCOUNT b ON b._SOURCE_ROW = v.source_row WHERE v.opened_on IS NULL AND b."opened_on" IS NOT NULL
UNION ALL
SELECT 'account', 'status not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_ACCOUNT v JOIN BRONZE.CORE_B_DEPOSIT_ACCOUNT b ON b._SOURCE_ROW = v.source_row WHERE v.status IS NULL AND b."acct_status" IS NOT NULL
UNION ALL
SELECT 'account', 'balance_usd not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_ACCOUNT v JOIN BRONZE.CORE_B_DEPOSIT_ACCOUNT b ON b._SOURCE_ROW = v.source_row WHERE v.balance_usd IS NULL AND b."ledger_balance" IS NOT NULL
UNION ALL
SELECT 'transaction' AS entity, 'rows' AS check_name, COUNT(*) AS failures, 'information' AS rule FROM SILVER.CORE_B_TRANSACTION
UNION ALL
SELECT 'transaction', 'key is null', COUNT(*), 'must be 0' FROM SILVER.CORE_B_TRANSACTION WHERE source_key IS NULL
UNION ALL
SELECT 'transaction', 'duplicate keys', COUNT(*) - COUNT(DISTINCT source_key), 'must be 0' FROM SILVER.CORE_B_TRANSACTION
UNION ALL
SELECT 'transaction', 'posted_at not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_TRANSACTION v JOIN BRONZE.CORE_B_TXN b ON b._SOURCE_ROW = v.source_row WHERE v.posted_at IS NULL AND b."txn_timestamp" IS NOT NULL
UNION ALL
SELECT 'transaction', 'txn_type not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_TRANSACTION v JOIN BRONZE.CORE_B_TXN b ON b._SOURCE_ROW = v.source_row WHERE v.txn_type IS NULL AND b."txn_type_desc" IS NOT NULL
UNION ALL
SELECT 'transaction', 'amount_signed_usd not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_TRANSACTION v JOIN BRONZE.CORE_B_TXN b ON b._SOURCE_ROW = v.source_row WHERE v.amount_signed_usd IS NULL AND b."amount" IS NOT NULL
UNION ALL
SELECT 'transaction', 'channel not parsed or not mapped', COUNT(*), 'must be 0' FROM SILVER.CORE_B_TRANSACTION v JOIN BRONZE.CORE_B_TXN b ON b._SOURCE_ROW = v.source_row WHERE v.channel IS NULL AND b."channel_desc" IS NOT NULL
UNION ALL
SELECT 'account', 'orphan accounts (no customer)', COUNT(*), 'report' FROM SILVER.CORE_B_ACCOUNT a LEFT JOIN SILVER.CORE_B_CUSTOMER c ON c.record_id = a.customer_key WHERE c.record_id IS NULL
UNION ALL
SELECT 'transaction', 'orphan transactions (no account)', COUNT(*), 'report' FROM SILVER.CORE_B_TRANSACTION t LEFT JOIN SILVER.CORE_B_ACCOUNT a ON a.record_id = t.account_key WHERE a.record_id IS NULL
ORDER BY 1, 2;
