"""F7 without AI: build a case narrative from a frozen evidence snapshot and reviewed templates.

  gather_evidence(party_id, execute) -> dict   every fact the narrative uses (JSON-serialisable)
  render_narrative(evidence)          -> str    Markdown, deterministic: same evidence, same text

Nothing is generated by a model. Sentences come from outputs/templates/reasons.yaml; numbers, dates and
names come from the evidence snapshot; policy pages come from SEARCH.POLICY_CHUNK. The snapshot is stored
with the output (outputs/case_store.py), so any output can be re-rendered and checked later.
"""
import hashlib
import json
import re
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

import yaml

TEMPLATES = Path(__file__).resolve().parent / "templates"
REASONS = yaml.safe_load((TEMPLATES / "reasons.yaml").read_text())
GENERATOR = "outputs/narrative.py; templates " + REASONS["template_version"]


def _q(execute, sql):
    df = execute(sql)
    df.columns = [c.lower() for c in df.columns]
    return df


def _plain(v):
    if v is None:
        return None
    if isinstance(v, float) and v != v:            # NaN
        return None
    if hasattr(v, "item"):
        v = v.item()
    if isinstance(v, Decimal):
        return float(v)
    if isinstance(v, (datetime, date)):
        return v.isoformat(sep=" ") if isinstance(v, datetime) else v.isoformat()
    if hasattr(v, "isoformat"):
        return str(v)
    return v


DATE_KEYS = ("_date", "_on", "_from", "_to", "as_of")


def _norm(k, v):
    """Same text from DuckDB and Snowflake: timestamps as 'YYYY-MM-DD HH:MM:SS', dates as 'YYYY-MM-DD'."""
    v = _plain(v)
    if v is None or not isinstance(v, str) or not re.match(r"\d{4}-\d{2}-\d{2}", v):
        return v
    if k.endswith("_at"):
        return v.replace("T", " ")[:19]
    if k.endswith(DATE_KEYS):
        return v[:10]
    return v


def _records(df):
    return [{k: _norm(k, v) for k, v in row.items()} for row in df.to_dict("records")]


def _commas(text):
    """'$28810' -> '$28,810' in the engine's evidence sentences."""
    return re.sub(r"\$(\d{4,})(?![\d,])", lambda m: f"${int(m.group(1)):,}", text or "")


def money(x):
    return f"${float(x):,.2f}"


def gather_evidence(party_id, execute):
    if not re.fullmatch(r"PTY_[0-9a-f]{8,32}", party_id or ""):
        raise ValueError("bad party id")
    p = f"'{party_id}'"
    prof = _records(_q(execute, f"""SELECT party_id, display_name, party_kind, cores, core_a_key, core_b_key
                                    FROM GOLD.PARTY WHERE party_id = {p}"""))
    if not prof:
        raise ValueError(f"unknown customer {party_id}")
    params = {r["name"]: r["num_value"] for r in _records(_q(execute, "SELECT name, num_value FROM GOLD.CONFIG_PARAM"))}
    signals = _records(_q(execute, f"""SELECT rule_code, weight, evidence_text, amount_usd, evidence_count,
                                       evidence_from, evidence_to FROM GOLD.RISK_SIGNAL
                                       WHERE party_id = {p} ORDER BY weight DESC, rule_code"""))
    risk = _records(_q(execute, f"""SELECT s.risk_score, s.raw_score, q.queue_rank, q.queue_size
                                    FROM GOLD.RISK_SCORE s LEFT JOIN GOLD.ALERT_QUEUE q ON q.party_id = s.party_id
                                    WHERE s.party_id = {p} ORDER BY q.queue_rank LIMIT 1"""))
    as_of = _records(_q(execute, "SELECT MAX(posted_date) AS as_of FROM GOLD.TRANSACTION"))[0]["as_of"]
    # the review window: the cash rules' own window if one fired, otherwise the last 30 days
    cash_sig = [s for s in signals if s["rule_code"] in ("XCORE_CASH_30D", "NEAR_THRESHOLD_CASH") and s["evidence_from"]]
    if cash_sig:
        w_from = min(s["evidence_from"] for s in cash_sig)
        w_to = max(s["evidence_to"] for s in cash_sig)
    else:
        w_from = _records(_q(execute, f"SELECT CAST(DATE '{as_of}' - 29 AS DATE) AS window_date"))[0]["window_date"]
        w_to = as_of
    deposits = _records(_q(execute, f"""SELECT posted_at, posted_date, source_system, account_id, branch, amount_usd,
                                        ctr_filed, source_file, source_row FROM GOLD.TRANSACTION
                                        WHERE party_id = {p} AND txn_type = 'CASH_DEPOSIT'
                                          AND posted_date BETWEEN DATE '{w_from}' AND DATE '{w_to}'
                                        ORDER BY posted_at, source_system, source_row"""))
    outflows = _records(_q(execute, f"""SELECT posted_at, posted_date, source_system, txn_type, amount_usd, counterparty,
                                        counterparty_institution, source_file, source_row FROM GOLD.TRANSACTION
                                        WHERE party_id = {p} AND txn_type IN ('WIRE_OUT', 'ACH_DEBIT')
                                          AND amount_usd >= {params.get('thresholds.ctr_cash_threshold_usd', 10000)}
                                          AND posted_date BETWEEN DATE '{w_from}' AND CAST(DATE '{w_to}' + 30 AS DATE)
                                        ORDER BY posted_at"""))
    kyc = _records(_q(execute, f"""SELECT source_system, occupation, expected_monthly_cash_usd, risk_rating, review_date,
                                   source_file, source_row FROM GOLD.KYC_PROFILE WHERE party_id = {p}
                                   ORDER BY source_system"""))
    alerts = _records(_q(execute, f"""SELECT alert_id, scenario, alert_date, status FROM GOLD.ALERT
                                      WHERE party_id = {p} ORDER BY alert_date"""))
    wanted = sorted({REASONS["reasons"][s["rule_code"]]["policy"] for s in signals if s["rule_code"] in REASONS["reasons"]}
                    | {x for a in REASONS["actions"].values() for x in a["policy"]})
    in_list = ", ".join("'" + w.replace("'", "''") + "'" for w in wanted)
    policy = {r["section"]: r for r in _records(_q(execute, f"""SELECT section, parent_section, page, document
                                   FROM SEARCH.POLICY_CHUNK WHERE section IN ({in_list})"""))}
    return {"party": prof[0], "risk": risk[0] if risk else None, "signals": signals, "as_of": as_of,
            "window": {"from": w_from, "to": w_to}, "cash_deposits": deposits, "outflows": outflows,
            "kyc": kyc, "legacy_alerts": alerts, "policy": policy,
            "thresholds": {"ctr_usd": params.get("thresholds.ctr_cash_threshold_usd"),
                           "legacy_per_core_usd": params.get("thresholds.legacy_per_core_cash_30d_usd")},
            "generator": GENERATOR}


def evidence_json(ev):
    return json.dumps(ev, sort_keys=True, separators=(",", ":"), default=str)


def sha256(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _cite(ev, section):
    p = ev["policy"].get(section)
    if not p:
        return f"BSA/AML Policy, section {section}"
    return f"BSA/AML Policy v7.2, section {section}, page {p['page']}"


def render_narrative(ev, author="", status="DRAFT"):
    party, sig, dep = ev["party"], ev["signals"], ev["cash_deposits"]
    name = party["display_name"].title()
    t = ev["thresholds"]
    by_core = {}
    for d in dep:
        c = by_core.setdefault(d["source_system"], {"n": 0, "usd": 0.0})
        c["n"] += 1
        c["usd"] += d["amount_usd"]
    total = sum(c["usd"] for c in by_core.values())
    core_label = {"core_a": "Core A", "core_b": "Core B"}
    split = "; ".join(f"{core_label[k]} {money(v['usd'])} in {v['n']} deposits" for k, v in sorted(by_core.items()))
    lines = [f"# Case narrative: {name}", "",
             f"**Status: {status}.** No output is final until approved by someone other than its author. "
             f"Synthetic demo data.", "",
             f"Customer: {name} ({party['party_kind'].lower()}), resolved across "
             f"{'both cores' if party['cores'] == 2 else 'one core'} "
             f"(Core A {party['core_a_key'] or '-'}, Core B {party['core_b_key'] or '-'}). "
             f"Review window {ev['window']['from']} to {ev['window']['to']}; data as of {ev['as_of']}.", ""]
    if ev["risk"]:
        r = ev["risk"]
        rank = f", rank {int(r['queue_rank'])} of {int(r['queue_size'])} in the alert queue" if r.get("queue_rank") else ""
        lines += [f"Risk score {r['risk_score']:.0f} of 100{rank}. Legacy alerts on this customer: {len(ev['legacy_alerts'])}.", ""]

    # 1. summary
    lines += ["## 1. Summary", ""]
    if dep:
        facts = [f"{name} deposited {money(total)} in cash across {'both cores' if len(by_core) == 2 else 'one core'} "
                 f"between {dep[0]['posted_date']} and {dep[-1]['posted_date']}: {split}."]
        if t["ctr_usd"] and all(d["amount_usd"] < t["ctr_usd"] for d in dep):
            facts.append(f"Each deposit was under ${t['ctr_usd']:,.0f}.")
        if t["legacy_per_core_usd"] and len(by_core) == 2 and all(v["usd"] < t["legacy_per_core_usd"] for v in by_core.values()):
            facts.append(f"Each core stayed under its ${t['legacy_per_core_usd']:,.0f} legacy rule, so neither legacy "
                         f"monitoring system could see the combined total.")
        days = {}
        for d in dep:
            days.setdefault(d["posted_date"], []).append(d)
        for day, ds in sorted(days.items()):
            cores = {d["source_system"] for d in ds}
            amt = sum(d["amount_usd"] for d in ds)
            if len(cores) == 2 and t["ctr_usd"] and amt > t["ctr_usd"] and not any(d["ctr_filed"] for d in ds):
                facts.append(f"Same-day cross-core cash on {day} totalled {money(amt)} with no CTR filed.")
        lines += [" ".join(facts), ""]
    else:
        lines += ["No cash deposits in the review window.", ""]
    if ev["outflows"]:
        outs = "; ".join(f"{o['txn_type'].replace('_', ' ').lower()} {money(o['amount_usd'])} to "
                         f"{o['counterparty'] or 'an unnamed counterparty'} on {o['posted_date']}" for o in ev["outflows"])
        lines += [f"Funds then left the relationship: {outs}.", ""]

    # 2. KYC
    lines += ["## 2. What the KYC files say", ""]
    if ev["kyc"]:
        for k in ev["kyc"]:
            lines.append(f"- {core_label.get(k['source_system'], k['source_system'])}: occupation or business "
                         f"'{k['occupation']}', KYC expected cash {money(k['expected_monthly_cash_usd'])} a month, "
                         f"risk rating {k['risk_rating']}, reviewed {k['review_date']}.")
        exp = max(k["expected_monthly_cash_usd"] for k in ev["kyc"])
        if dep and exp:
            lines.append(f"- Observed cash in the window was {total / exp:.1f} times the highest KYC expected monthly cash.")
    else:
        lines.append("- No KYC summary on file.")
    lines.append("")

    # 3. reasons
    lines += ["## 3. Why this customer was prioritised", ""]
    cited = []
    for s in sig:
        tmpl = REASONS["reasons"].get(s["rule_code"])
        if not tmpl:
            continue
        cite = _cite(ev, tmpl["policy"])
        cited.append(cite)
        lines.append(f"- **{tmpl['heading']}** ({s['rule_code']}, weight {s['weight']:+.0f}). "
                     + tmpl["text"].format(evidence=_commas(s["evidence_text"])) + f" [{cite}]")
    if not sig:
        lines.append("- No risk rules fired.")
    lines.append("")

    # 4. recommended action
    score = ev["risk"]["risk_score"] if ev["risk"] else 0
    act = REASONS["actions"]["escalate" if score >= REASONS["escalate_min_score"] else "review"]
    act_cites = [_cite(ev, s) for s in act["policy"]]
    cited += act_cites
    lines += ["## 4. Recommended next step", "", act["text"] + " [" + "; ".join(act_cites) + "]", ""]

    # 5. transactions
    lines += ["## 5. Transactions relied on", "", "| Date and time | Core | Type | Amount | Branch or counterparty | Source |",
              "| --- | --- | --- | --- | --- | --- |"]
    for d in dep:
        lines.append(f"| {d['posted_at']} | {core_label.get(d['source_system'])} | cash deposit | {money(d['amount_usd'])} | "
                     f"{d['branch'] or ''} | {d['source_file']} row {d['source_row']} |")
    for o in ev["outflows"]:
        lines.append(f"| {o['posted_at']} | {core_label.get(o['source_system'])} | {o['txn_type'].replace('_', ' ').lower()} | "
                     f"{money(o['amount_usd'])} | {o['counterparty'] or ''} | {o['source_file']} row {o['source_row']} |")
    lines.append("")

    # 6. sources
    lines += ["## 6. Sources", ""]
    for c in sorted(set(cited)):
        lines.append(f"- {c}")
    for k in ev["kyc"]:
        lines.append(f"- KYC summary, {k['source_file']} row {k['source_row']}")
    lines += ["", "---", f"Prepared by {author or 'unassigned'} with {ev['generator']}. Built from rules and reviewed "
              "templates; no AI was used. Every figure above comes from the evidence snapshot stored with this output."]
    return "\n".join(lines) + "\n"
